/**
 * Replace placeholder tokens in source with generated image paths from generation-state.json.
 *
 * Usage:
 *   node scripts/image-pipeline/apply.mjs
 *   node scripts/image-pipeline/apply.mjs --dry-run
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { PLACEHOLDER_PATTERN } from "./config.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "../..");
const SRC = path.join(ROOT, "src");
const STATE = path.join(__dirname, "generation-state.json");

function walk(dir, files = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, files);
    else if (/\.(tsx?|jsx?)$/.test(entry.name)) files.push(full);
  }
  return files;
}

function main() {
  const dryRun = process.argv.includes("--dry-run");

  if (!fs.existsSync(STATE)) {
    console.error("No generation-state.json — run generate.mjs first");
    process.exit(1);
  }

  const { completed } = JSON.parse(fs.readFileSync(STATE, "utf8"));
  const mapping = Object.fromEntries(
    Object.entries(completed).map(([id, meta]) => [id, meta.outputPath])
  );

  let totalReplacements = 0;
  const files = walk(SRC);

  for (const file of files) {
    let content = fs.readFileSync(file, "utf8");
    let changed = false;

    content = content.replace(new RegExp(PLACEHOLDER_PATTERN.source, "g"), (token) => {
      if (!mapping[token]) return token;
      changed = true;
      totalReplacements++;
      return mapping[token];
    });

    if (changed) {
      if (dryRun) {
        console.log("Would update:", path.relative(ROOT, file));
      } else {
        fs.writeFileSync(file, content, "utf8");
        console.log("Updated:", path.relative(ROOT, file));
      }
    }
  }

  console.log(`\n${dryRun ? "Would replace" : "Replaced"} ${totalReplacements} placeholder(s) in source`);

  writeCategoryImagesModule(completed, dryRun);
  writeAboutUsDefaultsPatch(completed, dryRun);
}

function writeCategoryImagesModule(completed, dryRun) {
  const entries = Object.entries(completed).filter(([id]) => id.startsWith("CATEGORY_IMAGE_"));
  if (!entries.length) return;

  const lines = entries.map(([id, meta]) => {
    const slug = id
      .replace(/^CATEGORY_IMAGE_/, "")
      .replace(/_URL$/, "")
      .toLowerCase()
      .replace(/_/g, "-");
    return `  "${slug}": "${meta.outputPath}",`;
  });

  const outPath = path.join(SRC, "lib/generated/categoryImages.ts");
  const content = `/** Auto-generated by scripts/image-pipeline/apply.mjs — do not edit manually */\nexport const categoryImages: Record<string, string> = {\n${lines.join("\n")}\n};\n`;

  if (dryRun) {
    console.log(`Would write ${entries.length} category paths → ${path.relative(ROOT, outPath)}`);
    return;
  }

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, content, "utf8");
  console.log(`Wrote categoryImages.ts (${entries.length} entries)`);
}

function writeAboutUsDefaultsPatch(completed, dryRun) {
  const aboutEntries = Object.entries(completed).filter(([id]) => id.startsWith("ABOUT_US_"));
  if (!aboutEntries.length) return;

  const defaultsPath = path.join(SRC, "lib/aboutUsDefaults.ts");
  let content = fs.readFileSync(defaultsPath, "utf8");
  let changed = false;

  for (const [id, meta] of aboutEntries) {
    // ABOUT_US_HERO_HEROIMAGE → hero.heroImage
    const parts = id.replace(/^ABOUT_US_/, "").toLowerCase().split("_");
    const section = parts[0];
    const field = parts.slice(1).join("");
    const fieldKey = field === "heroimage" ? "heroImage" : field === "backgroundimage" ? "backgroundImage" : "image";

    const re = new RegExp(`(${section}:\\s*\\{[\\s\\S]*?${fieldKey}:\\s*)ABOUT_US_PLACEHOLDER`);
    if (re.test(content)) {
      content = content.replace(re, `$1"${meta.outputPath}"`);
      changed = true;
    }
  }

  if (!changed) return;
  if (dryRun) {
    console.log("Would update aboutUsDefaults.ts with generated about-us images");
    return;
  }
  fs.writeFileSync(defaultsPath, content, "utf8");
  console.log("Updated aboutUsDefaults.ts");
}

main();
